# Generated by Django 5.0.1 on 2024-01-30 16:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='bio',
            field=models.TextField(blank=True, help_text='Give your viewers key details about what you do. Can include html.'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='cv',
            field=models.FileField(blank=True, help_text='file size must not exceed 2621440', null=True, upload_to='cv'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='display_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='facebook',
            field=models.URLField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='github',
            field=models.URLField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='instagram',
            field=models.URLField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='linked_in',
            field=models.URLField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='location',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='whatsap',
            field=models.URLField(blank=True, max_length=300),
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('Professional', 'Professional'), ('Personal', 'Personal')], max_length=12)),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.userprofile')),
            ],
        ),
    ]
