# Generated by Django 5.0.1 on 2024-01-30 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_userprofile_bio_userprofile_cv_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill',
            name='user_profile',
        ),
        migrations.AddField(
            model_name='skill',
            name='user_profile',
            field=models.ManyToManyField(related_name='skills', to='users.userprofile'),
        ),
    ]
