# Generated by Django 5.0.1 on 2024-01-30 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='titles',
            field=models.ManyToManyField(related_name='users', to='users.title'),
        ),
    ]
