# Generated by Django 5.0.1 on 2024-01-30 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_userprofile_skills_alter_userprofile_titles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='skills',
            field=models.ManyToManyField(blank=True, to='users.skill'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='titles',
            field=models.ManyToManyField(blank=True, to='users.title'),
        ),
    ]
