# Generated by Django 5.0.1 on 2024-01-30 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_userprofile_skills_alter_userprofile_titles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='name',
            field=models.CharField(help_text='eg. UI/UX', max_length=255),
        ),
        migrations.AlterField(
            model_name='title',
            name='name',
            field=models.CharField(help_text='eg. UI/UX Designer', max_length=255),
        ),
    ]
