# Generated by Django 5.0.1 on 2024-01-31 00:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_skill_name_alter_title_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='whatsap',
            new_name='whatsapp',
        ),
    ]
