# Generated by Django 5.0.1 on 2024-01-31 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_rename_whatsap_userprofile_whatsapp'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='twitter',
            field=models.URLField(blank=True, max_length=300),
        ),
    ]
