# Generated by Django 5.0.1 on 2024-01-31 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_userprofile_twitter'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='cover',
            field=models.ImageField(blank=True, help_text='Override the default cover photo', null=True, upload_to='cover'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='profile_photo',
            field=models.ImageField(blank=True, help_text='A handsome job enticing photo of yourself', null=True, upload_to='cover'),
        ),
    ]
